/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_gaoweili_myjni_NdkJniUtils */

#ifndef _Included_com_example_gaoweili_myjni_NdkJniUtils
#define _Included_com_example_gaoweili_myjni_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_gaoweili_myjni_NdkJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_gaoweili_myjni_NdkJniUtils_getCLanguageString
        (JNIEnv *, jobject);

/*
 * Class:     com_example_gaoweili_myjni_NdkJniUtils
 * Method:    getMyNamee
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_gaoweili_myjni_NdkJniUtils_getMyNamee
        (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_example_gaoweili_myjni_NdkJniUtils
 * Method:    getMyAge
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_example_gaoweili_myjni_NdkJniUtils_getMyAge
        (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_example_gaoweili_myjni_NdkJniUtils
 * Method:    getIsRight
 * Signature: (Ljava/lang/String;IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_gaoweili_myjni_NdkJniUtils_getIsRight
        (JNIEnv *, jobject, jstring, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
