/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_gaoweili_myjni_NdkJniUtils */

#ifndef _Included_com_example_gaoweili_myjni_NdkJniUtils
#define _Included_com_example_gaoweili_myjni_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_gaoweili_myjni_NdkJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_gaoweili_myjni_NdkJniUtils_getCLanguageString
        (JNIEnv *, jobject);

/*
 * Class:     com_example_gaoweili_myjni_NdkJniUtils
 * Method:    getMyname
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_gaoweili_myjni_NdkJniUtils_getMyname
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
